<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="38578" started-at="2017-03-19T18:45:57Z" finished-at="2017-03-19T18:46:36Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="38578" started-at="2017-03-19T18:45:57Z" finished-at="2017-03-19T18:46:36Z">
      <class name="com.seleniumeasy.tests.NewTest">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.seleniumeasy.tests.NewTest@1bd9247]" name="beforeSuite" is-config="true" duration-ms="37" started-at="2017-03-20T00:15:57Z" finished-at="2017-03-20T00:15:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.seleniumeasy.tests.NewTest@1bd9247]" name="beforeTest" is-config="true" duration-ms="0" started-at="2017-03-20T00:15:57Z" finished-at="2017-03-20T00:15:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.seleniumeasy.tests.NewTest@1bd9247]" name="beforeClass" is-config="true" duration-ms="1" started-at="2017-03-20T00:15:57Z" finished-at="2017-03-20T00:15:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.seleniumeasy.tests.NewTest@1bd9247]" name="beforeMethod" is-config="true" duration-ms="15606" started-at="2017-03-20T00:15:57Z" finished-at="2017-03-20T00:16:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="f()[pri:0, instance:com.seleniumeasy.tests.NewTest@1bd9247]" name="f" duration-ms="2044" started-at="2017-03-20T00:16:13Z" finished-at="2017-03-20T00:16:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Wrong message expected [sandip singh] but found [sandip]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Wrong message expected [sandip singh] but found [sandip]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.seleniumeasy.tests.NewTest.f(NewTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.seleniumeasy.tests.NewTest@1bd9247]" name="afterMethod" is-config="true" duration-ms="1578" started-at="2017-03-20T00:16:15Z" finished-at="2017-03-20T00:16:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.seleniumeasy.tests.NewTest@1bd9247]" name="beforeMethod" is-config="true" duration-ms="16470" started-at="2017-03-20T00:16:16Z" finished-at="2017-03-20T00:16:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="f1()[pri:0, instance:com.seleniumeasy.tests.NewTest@1bd9247]" name="f1" duration-ms="1910" started-at="2017-03-20T00:16:33Z" finished-at="2017-03-20T00:16:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Wrong message expected [sandip singh] but found [sandip]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Wrong message expected [sandip singh] but found [sandip]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.seleniumeasy.tests.NewTest.f1(NewTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f1 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.seleniumeasy.tests.NewTest@1bd9247]" name="afterMethod" is-config="true" duration-ms="948" started-at="2017-03-20T00:16:35Z" finished-at="2017-03-20T00:16:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.seleniumeasy.tests.NewTest@1bd9247]" name="afterClass" is-config="true" duration-ms="0" started-at="2017-03-20T00:16:36Z" finished-at="2017-03-20T00:16:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.seleniumeasy.tests.NewTest@1bd9247]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-03-20T00:16:36Z" finished-at="2017-03-20T00:16:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.seleniumeasy.tests.NewTest@1bd9247]" name="afterSuite" is-config="true" duration-ms="0" started-at="2017-03-20T00:16:36Z" finished-at="2017-03-20T00:16:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.seleniumeasy.tests.NewTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
